name: iotbox-heartbeat
summary: IoTBox Heartbeat Service
description: IoTBox Heartbeat Service
version: git

base: core24
confinement: strict
grade: stable

platforms:
  amd64:
  arm64:
  armhf:

apps:
  daemon:
    command: bin/heartbeat.sh
    daemon: simple
    restart-condition: always
    restart-delay: 60s
    plugs: [network]
  heartbeat:
    command: bin/heartbeat.sh
    plugs: [network]

parts:
  cli:
    plugin: go
    source: https://github.com/nats-io/natscli.git
    source-tag: v0.2.4
    build-snaps:
      - go
    override-pull: |
      craftctl default
      rm -rf nats/tests
  overlay:
    plugin: dump
    source: overlay
